/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package universidadejemplo.Vistas;

/**
 *
 * @author Celia
 */
public class UniversidadG12 extends javax.swing.JFrame {

    /**
     * Creates new form UniversidadG12
     */
    public UniversidadG12() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JMBOpc = new javax.swing.JMenuBar();
        JMAlumno = new javax.swing.JMenu();
        JMFormAlum = new javax.swing.JMenuItem();
        JMMateria = new javax.swing.JMenu();
        JMIFormMat = new javax.swing.JMenuItem();
        JMAdmin = new javax.swing.JMenu();
        JMInsc = new javax.swing.JMenuItem();
        JMIManipNot = new javax.swing.JMenuItem();
        JMConsultas = new javax.swing.JMenu();
        JMIAlumPorMat = new javax.swing.JMenuItem();
        JMSalir = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gestion de Alumnos");

        JMAlumno.setText("Alumno");

        JMFormAlum.setText("Formulario de Alumno");
        JMAlumno.add(JMFormAlum);

        JMBOpc.add(JMAlumno);

        JMMateria.setText("Materia");

        JMIFormMat.setText("Formulario de Materia");
        JMMateria.add(JMIFormMat);

        JMBOpc.add(JMMateria);

        JMAdmin.setText("Administracion");

        JMInsc.setText("Manejo de Inscripciones");
        JMAdmin.add(JMInsc);

        JMIManipNot.setText("Manipulacion de Notas");
        JMAdmin.add(JMIManipNot);

        JMBOpc.add(JMAdmin);

        JMConsultas.setText("Consultas");

        JMIAlumPorMat.setText("Alumnos por Materia");
        JMConsultas.add(JMIAlumPorMat);

        JMBOpc.add(JMConsultas);

        JMSalir.setText("Salir");
        JMBOpc.add(JMSalir);

        setJMenuBar(JMBOpc);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 277, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UniversidadG12.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UniversidadG12.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UniversidadG12.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UniversidadG12.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UniversidadG12().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu JMAdmin;
    private javax.swing.JMenu JMAlumno;
    private javax.swing.JMenuBar JMBOpc;
    private javax.swing.JMenu JMConsultas;
    private javax.swing.JMenuItem JMFormAlum;
    private javax.swing.JMenuItem JMIAlumPorMat;
    private javax.swing.JMenuItem JMIFormMat;
    private javax.swing.JMenuItem JMIManipNot;
    private javax.swing.JMenuItem JMInsc;
    private javax.swing.JMenu JMMateria;
    private javax.swing.JMenu JMSalir;
    // End of variables declaration//GEN-END:variables
}
